name: TestJava
version: '3.2'
main: TestJava.testjava.TestJava
api-version: 1.20
authors: [ Edouard ]
description: TestJava
commands:
  delegation:
    description: Envoyer une lettre
    usage: /delegation <pseudo>
  rename:
    description: Renommer le village actuel
    usage: /rename <newVillageName>
  war:
    description: Déclarer la guerre
    usage: /war <villageName>
  village:
    description: Voir les infos d'un village
    usage: /village <villageName>
  marketprice:
    description: Voir les infos du cours du marché
    usage: /marketprice <buy|sell> <resourceName>
  market:
    description: Acheter ou vendre une ressource tenue en main
    usage: /market <buy|sell> <resourceName> <resourceQuantity>
  money:
    description: Voir son argent
    usage: /money <playerName>
  nearest:
    description: Voir le village près de soi
    usage: /nearest
  build:
    description: Créer un bâtiment
    usage: /nearest <buildingName[bergerie]>